name: Api Pipeline Workflow

on:
  workflow_dispatch:
    inputs:
    
      akamai_network:
        description: 'Select Akamai network'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          
      environment:
        description: 'Select Environment'
        required: false
        default: 'tst1'
        type: choice
        options:
          - tst1
          - stg1

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'tvamsi66/devops'
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS }}
          event-type: 'trigger-devops-main-workflow'
          client-payload: '{"data": "${{ github.event.inputs.user_input_data }}"}'
