name: Api Pipeline Workflow

on:
  workflow_dispatch:
    inputs:
    
      akamai_network:
        description: 'Select Akamai network'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          
      environment:
        description: 'Select Environment'
        required: false
        default: 'tst1'
        type: choice
        options:
          - tst1
          - stg1

jobs:
  invoke-akamai-deploy-workflow:
    runs-on: ubuntu-latest
    env: 
      REPOSITORY: "CDN-pipe-api-rccl-com"
      PIPELINE_NAME: "api-rccl-com"
      PROPERTY_NAME: "api.rccl.com"
    steps:
      - name: Set payload
        id: set_payload
        run: echo "::set-output name=payload::{\"repository\":\"$REPOSITORY\",\"pipeline_name\":\"$PIPELINE_NAME\", \"property_name\":\"$PROPERTY_NAME\", \"akamai_network\":\"${{ github.event.inputs.akamai_network }}\", \"environment\":\"${{ github.event.inputs.environment }}\"}"
      - name: Trigger Docker Build and Deploy to Akamai workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'tvamsi66/devops'
          event-type: 'akamai-deploy-workflow'          
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS }}
          client-payload: ${{ steps.set_payload.outputs.payload }}
