name: Trigger Devops Private Workflow

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Name of the repository to trigger the workflow in (e.g., owner/repo)'
        required: true
      workflow:
        description: 'Type of the event to trigger in the external repository (e.g., trigger-external-workflow)'
        required: true
      data:
        description: 'Optional data to pass to the triggered workflow'
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'tvamsi66/devops'
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS }}
          event-type: 'trigger-devops-private-workflow'
          client-payload: '{"data": "Sample data to pass to the triggered workflow"}'
